@endpoint=http://localhost:4000

############################################# PLACES OK

### /places GET ALL PLACES ------------- OK
GET {{endpoint}}/places 

### /places CREATE PLACE ------------- OK
POST {{endpoint}}/places
Content-Type: application/json

{
    "name": "Le parc de la tête d'Or",
    "journey": "Pour y aller prenez vos deux jambes et marchez",
    "description": "Le parc de la tête d'Or est un parc urbain de Lyon, situé dans le 6ᵉ arrondissement de Lyon, en France. Avec une superficie de 117 hectares, il est l'un des plus grands parcs urbains de France.",
    "user_id": "4"
}

### /places GET ONE PLACE ------------- OK
GET {{endpoint}}/places/11 

### /places UPDATE PLACE  ------------- OK
PATCH {{endpoint}}/places/8
Content-Type: application/json

{
    "name": "Le parc",
    "journey": [
        "Pour y aller", 
        "prenez vos deux jambes", 
        "ET VOS PIEDS", 
        "et marchez"
        ],
    "description": "Le parc de la tête d'Or est un parc urbain de Lyon, situé dans le 6ᵉ arrondissement de Lyon, en France. Avec une superficie de 117 hectares, il est l'un des plus grands parcs urbains de France."
}

### /places DELETE PLACE ------------- OK
DELETE {{endpoint}}/places/10

############################################# LOGIN OK

### / login LOGIN ------------- OK
POST {{endpoint}}/login
Content-Type: application/json

{
    "email": "Doobi@yahoo.com",
    "password": "#1gKiJItKHLNp2"
}

############################################# REGISTER OK

### /register CREATE NEW USER ------------- OK
POST {{endpoint}}/register
Content-Type: application/json

{
    "username": "Gloubidoo",
    "email": "Gloubiboo@youhou.com",
    "password": "#1gKiJItKHLNp2",
    "passwordConfirm": "#1gKiJItKHLNp2"
}

############################################# USER OK

### /user GET ONE USER ------------- OK
GET {{endpoint}}/user/2

### /user UPDATE USER ------------- OK
PATCH {{endpoint}}/user/6
Content-Type: application/json

{
    "username": "Doobidooh Doo doo",
    "email": "HOdoobibi@yahoo.com",
    "password": "#1gKiJItKHLNp2"
}

### /user DELETE USER ------------- OK
DELETE {{endpoint}}/user/1

