@endpoint=http://localhost:4000

### Home
GET {{endpoint}}/

### getall
GET {{endpoint}}/register

### getallPlaces
GET {{endpoint}}/place

### login
POST {{endpoint}}/login
Content-Type: application/json

{
    "email": "Hazel.Muller@gmail.com",
    "password": "efzefze"
}

### Register
POST {{endpoint}}/register
Content-Type: application/json

{
    "username": "Charles",
    "email": "dbjkdhkjdhfkfdjsndoe@example.com",
    "password": "efEFze123fze"
}

### Delete User
DELETE {{endpoint}}/user/16
Content-Type: application/json
